### ISSUE TITLE
Include ability to scan multiple sources

### ISSUE THREAD

**Issue by arthurpalves** [arthurpalves/coherent-swift#12]

**Comment by timstudt** [comment]
wouldn't it make sense to support in .yml:
`
sources:
  - Sources/
  - Modules/**/Sources
  - ./*.swift
`
`PathKit` already supports globs so shouldn't be too big of a task.

**Comment by arthurpalves** [comment]
I plan to make a new release in 2 weeks. Will try to squeeze this one in there.
Or is this something you'd like to contribute to?

**Comment by timstudt** [comment]
I can give it a try. 
but it can get to a bigger task when considering fail scenarios, e.g. missing files/path.. so I'd start with a simple solution.
also it'd be better to have the yml parsing part unit tested first, that would increase implementation speed on dependant features IMO.

**Comment by arthurpalves** [comment]
Yes, that is the plan. I'm just tight on time.
There are probably some refactoring that needs to be done in order to unit test it properly as well.

Any help you can give is appreciated, otherwise I'll take a look when I get some time 🙌

**Comment by timstudt** [comment]
#52 PR waiting for review
