### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by timstudt** [arthurpalves/coherent-swift#48]
First off, really cool project.

I installed last release with Mint and it outputs: 

```
INFO  [2021-02-24 13:08:43]: ▸ File: Domain/<someFile>.swift
ERROR [2021-02-24 13:08:43]: ▸ --------------------------------------------------------------------------------------
ERROR [2021-02-24 13:08:43]: ▸ Analyzed 0 files with nan% overall cohesion. Threshold is 80%
```

But when cloning and building the project it works fine.
I've noticed that there's been quite a few code changes since last release, simply creating a new release would fix it, I think

**Comment by arthurpalves** [comment]
I totally forgot to release 0.5.9 🙃
[It's done now](https://github.com/arthurpalves/coherent-swift/releases/tag/0.5.9). Let me know if there are any issues with it and I'll take a look asap.

I'm also worked on improving the logs, as you can see below, but that will be released soon in 0.6.0. Noticed that it's miscalculating the usage of properties.
![Screenshot 2021-02-24 at 22 03 31](https://user-images.githubusercontent.com/1584586/109065606-23357f00-76ec-11eb-9e79-c0446621fd4d.png)
